import streamlit as st
import pandas as pd
from services.supabase_service import get_all_hazard_predictions

def render():
    """
    Renders Admin Hazard Predictions Inspector.
    """
    st.markdown(
        """
        <div style="margin-bottom: 16px;">
            <div style="display: flex; align-items: center; gap: 8px;">
                <span style="background: #dc2626; color: white; padding: 4px 8px; border-radius: 4px; font-size: 11px; font-weight: 800;">ADMIN</span>
                <h2 style="margin: 0; font-size: 22px; font-weight: 700; color: #f8fafc;">
                    Hazard Predictions Model Auditing & Logs
                </h2>
            </div>
            <p style="margin: 2px 0 0 0; font-size: 13px; color: #94a3b8;">
                Audit records from <code>hazard_predictions</code> table generated by the 7-hazard ML prediction pipeline
            </p>
        </div>
        """,
        unsafe_allow_html=True
    )

    records = get_all_hazard_predictions(limit=50)

    if not records:
        st.info("No hazard prediction records currently in database.")
        return

    # Summary table
    table_data = []
    for r in records:
        preds = r.get("predictions", {})
        table_data.append({
            "ID": r.get("id"),
            "Location": r.get("location"),
            "Inference Time": r.get("timestamp") or r.get("created_at"),
            "Rainfall Risk": preds.get("rainfall", {}).get("risk_level", "LOW"),
            "Thunderstorm Risk": preds.get("thunderstorm", {}).get("risk_level", "LOW"),
            "Flooding Risk": preds.get("flooding", {}).get("risk_level", "LOW"),
            "Heatwave Risk": preds.get("heatwave", {}).get("risk_level", "LOW"),
            "Fog Risk": preds.get("fog", {}).get("risk_level", "LOW"),
            "Dust Storm Risk": preds.get("dust_storm", {}).get("risk_level", "LOW"),
            "Strong Wind Risk": preds.get("strong_wind", {}).get("risk_level", "LOW")
        })

    st.dataframe(pd.DataFrame(table_data), use_container_width=True, hide_index=True)

    st.markdown("### 🔍 Raw JSON Prediction Payload Inspector")
    selected_id = st.selectbox("Select Record ID to Inspect:", [r.get("id") for r in records])
    selected_rec = next((r for r in records if r.get("id") == selected_id), None)

    if selected_rec:
        st.json(selected_rec)
